title: RandomVariable
description: A bio data science blog
theme: just-the-docs
url: https://aswatib.github.io/RandomVariable
baseurl: "/RandomVariable"
include: ['_images']

nav:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /RandomVariable/posts/
